### PR TITLE
Port to Gtk+ 3

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
Removed closeService() because that function is clearly not present in [usb4butia](https://github.com/sugarlabs/followmeButia/blob/master/pybot/usb4butia.py) file, which caused an error
```
Traceback (most recent call last):
  File "/home/yash/gssoc/followmeButia/main.py", line 131, in run
    self.r.butia.closeService()
AttributeError: USB4Butia instance has no attribute 'closeService'
```

@quozl please review!

### CODE REVIEW

**Comment by quozl** [comment]
I can't test, I don't have a USB4Butia device.  You will have to rely on the authors of the code.  Unless you can get a response from them, I don't think it is worth your time to port this activity.

**Comment by yell0wfl4sh** [comment]
@chimosky can you arrange required hardware for testing this activity?

**Comment by chimosky** [comment]
@yashagrawal3 sorry I can't arrange one, and I'm with @quozl on this one; if you contact them and response is taking too long we'll have to replace this with another activity.

**Comment by quozl** [comment]
Not replace, just ignore.  Has anyone contacted the authors?  Can you produce a USB4Butia device yourself from parts and any published firmware?

**Comment by chimosky** [comment]
> Not replace, just ignore.

I meant in our list of activities to be ported.

**Comment by yell0wfl4sh** [comment]
I have sent mail to @AlanJAS , who seems to be the author of this activity, I am waiting for his response.

**Comment by quozl** [comment]
@chimosky, oh, thanks, good idea.  Is the list kept anywhere in particular?  See sugar-devel@ for a list of Fedora packaged activities that need porting too.

**Comment by chimosky** [comment]
@quozl we have ours [here](https://trello.com/b/772ohz8X/gtk3-port) and we'll look at the ones mentioned in sugar-devel too.

**Comment by quozl** [comment]
Thanks, but;

> Board not found.
> This board may be private. You may be able to view it by logging in.

It would be nice to use GitHub gist, or a GitHub project.

**Pull request closed without merging**
